### PR TITLE
Update to MC 1.11

### PR DESCRIPTION
**Pull request by raoulvdberge**
This is the port for Tiny Progressions to MC 1.11.

- [x] Initial port
- [x] Version bump to TP 1.1.0
- [x] Make the cobblegen blocks use capabilities for items
- [x] Lowercase block names
- [x] Lowercase item ids
- [x] Handle migration for new ids correctly

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Done! Small things to note:

- Growth Crystals Tier 2 have a little rendering bug:
x

- Compressed Nether Star Block doesn't render at all:
x

The console reports this:
```
[17:13:49] [Client thread/ERROR] [TEXTURE ERRORS]:     Problem: broken aspect ratio and not an animation
[17:13:49] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks/nether_star_block_background.png
[17:13:49] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks/nether_star_block.png
```

**Comment by raoulvdberge** [comment]
One second, I'm bringing it up to date with bb296c0cb8d9c68eddce31b425067f99a9fa3f91...

**Comment by raoulvdberge** [comment]
Done. GH still reports merge conflicts, but the 1.11 changes should go in a new branch on your repository, not master.

**Comment by Kashdeya** [comment]
We have added a 1.11.2 branch if you would like to make a PR to that one.

**Comment by raoulvdberge** [comment]
I changed the base branch for this PR to your 1.11.x branch. I tried fixing the conflicts, but they would revert some of my ID changes, and, the majority of the changes are imports / whitespace. I think it's safe to say that we can force-merge.

**Comment by raoulvdberge** [comment]
What happened?

**Comment by Kashdeya** [comment]
im working on it lol.

**Pull request closed without merging**
